# Generated by Django 5.0.6 on 2024-07-04 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('fabricado_el', models.IntegerField(default=2024)),
                ('cantidad_puertas', models.IntegerField()),
                ('cilindrada', models.IntegerField()),
                ('tipo_combustible', models.CharField(max_length=50)),
                ('pais_fabricacion', models.CharField(max_length=50)),
                ('precio_dolares', models.IntegerField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.marca')),
            ],
        ),
    ]
