# Generated by Django 5.0.6 on 2024-10-09 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_autos_alter_product_options_alter_product_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autos',
            options={'verbose_name': 'Auto', 'verbose_name_plural': 'Autos'},
        ),
    ]
